# Generated by Django 5.0.3 on 2024-03-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=500)),
                ('firstName', models.CharField(max_length=500)),
                ('gmail', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
